### ISSUE TITLE
Hide (Bonus) Action for monsters 

### ISSUE THREAD

**Issue by Syrious** [Trekiros/battleSim#2]
First of all, huge thanks for that tool. It is really helpful!

So, I was reading a lot of [The Monsters Know What They're Doing](https://www.themonstersknow.com). Many night active and sneaky monsters like Goblins would typical use their ability to hide as often as they can. As described in the blog:

> A typical combat round for the goblins will go: Attack (action), move, Hide (bonus action). Because they’re attacking from hiding, they attack with advantage. Regardless of whether they hit or miss, the attack gives their position away, so they change it immediately, because they can. (The sequence is important. Whenever possible, a goblin must end its turn hidden; otherwise, it’s vulnerable. Move/Hide/Attack would achieve the same offensive result but leave the goblin exposed to retaliation between turns.)

It would be nice to see such tactics or the appropriate action reflected in the monster customization. Currently I use Invisibility Buff on Self as Bonus Action, but I'm not sure if the result would be the same.

**Comment by Trekiros** [comment]
Yup, invisibility is a pretty good analogue for what happens when a creature hides imo
I'll try and find every creature who can hide as a bonus action, and update their templates so they'll do that by default
